name: Weekly Portfolio Rebalance

on:
  schedule:
    # Každý pátek v 17:00 UTC (18:00 CET, po NYSE close v 16:00 ET)
    - cron: '0 17 * * 5'
  workflow_dispatch:  # Umožňuje manuální spuštění

env:
  PYTHON_VERSION: '3.10'
  TZ: 'Europe/Prague'

jobs:
  rebalance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Environment Variables
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          echo "ALPACA_API_KEY=$ALPACA_API_KEY" >> $GITHUB_ENV
          echo "ALPACA_SECRET_KEY=$ALPACA_SECRET_KEY" >> $GITHUB_ENV
          echo "POLYGON_API_KEY=$POLYGON_API_KEY" >> $GITHUB_ENV
          echo "Environment variables configured"
          
      - name: Fetch Market Data
        run: |
          echo "📊 Fetching latest market data..."
          python -m src.data.data_fetcher
          
      - name: Run Strategy Screening
        run: |
          echo "🎯 Running 5-strategy screening..."
          python -m src.screening.screener_engine --mode weekly
          
      - name: Evaluate RL Agent
        run: |
          echo "🤖 Evaluating current portfolio with RL agent..."
          python -m src.ml.evaluation
          
      - name: Generate Trade Signals
        run: |
          echo "📈 Generating rebalancing trade signals..."
          python -m src.trading.order_execution --mode dry-run
          
      - name: Train RL Agent
        run: |
          echo "🧠 Training RL agent on last week's performance..."
          python -m src.ml.training --episodes 100
          
      - name: Update Results
        run: |
          echo "💾 Saving results and metrics..."
          python -m src.utils.metrics --save
          
      - name: Commit and Push Results
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/results/
          git add data/models/
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Weekly rebalance $(date +'%Y-%m-%d')" && git push)
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weekly-results-${{ github.run_number }}
          path: |
            data/results/*.csv
            data/results/*.json
            data/models/*.pkl
          retention-days: 90
          
      - name: Send Notification (Optional)
        if: always()
        run: |
          echo "✅ Weekly rebalancing completed!"
          echo "Results saved and dashboard updated"
          # Optional: Send Telegram/Discord/Email notification
          # python -m src.utils.notifications --status ${{ job.status }}

  deploy-dashboard:
    needs: rebalance
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Trigger Streamlit Cloud Update
        run: |
          echo "🚀 Streamlit Cloud will auto-update from git push"
          echo "Dashboard accessible at your streamlit.io URL"
